const weatherData = [
    { country: "United States", temperature: 42, condition: "Sunny", humidity: 20, windSpeed: 15, flag: "https://flagcdn.com/w320/us.png" },
    { country: "Canada", temperature: 35, condition: "Partly Cloudy", humidity: 55, windSpeed: 12, flag: "https://flagcdn.com/w320/ca.png" },
    { country: "United Kingdom", temperature: 36, condition: "Sunny", humidity: 50, windSpeed: 10, flag: "https://flagcdn.com/w320/gb.png" },
    { country: "Germany", temperature: 37, condition: "Sunny", humidity: 45, windSpeed: 12, flag: "https://flagcdn.com/w320/de.png" },
    { country: "France", temperature: 39, condition: "Sunny", humidity: 40, windSpeed: 8, flag: "https://flagcdn.com/w320/fr.png" },
    { country: "Australia", temperature: 37, condition: "Partly Cloudy", humidity: 50, windSpeed: 14, flag: "https://flagcdn.com/w320/au.png" },
    { country: "Brazil", temperature: 40, condition: "Sunny", humidity: 30, windSpeed: 12, flag: "https://flagcdn.com/w320/br.png" },
    { country: "Japan", temperature: 38, condition: "Sunny", humidity: 60, windSpeed: 10, flag: "https://flagcdn.com/w320/jp.png" },
    { country: "India", temperature: 45, condition: "Sunny", humidity: 25, windSpeed: 20, flag: "https://flagcdn.com/w320/in.png" },
    { country: "Russia", temperature: 35, condition: "Partly Cloudy", humidity: 50, windSpeed: 15, flag: "https://flagcdn.com/w320/ru.png" },
    { country: "China", temperature: 42, condition: "Sunny", humidity: 35, windSpeed: 10, flag: "https://flagcdn.com/w320/cn.png" },
    { country: "Mexico", temperature: 36, condition: "Partly Cloudy", humidity: 55, windSpeed: 10, flag: "https://flagcdn.com/w320/mx.png" },
    { country: "South Africa", temperature: 36, condition: "Sunny", humidity: 40, windSpeed: 12, flag: "https://flagcdn.com/w320/za.png" },
    { country: "Italy", temperature: 41, condition: "Sunny", humidity: 30, windSpeed: 8, flag: "https://flagcdn.com/w320/it.png" },
    { country: "Spain", temperature: 44, condition: "Sunny", humidity: 25, windSpeed: 12, flag: "https://flagcdn.com/w320/es.png" },
    { country: "Argentina", temperature: 37, condition: "Partly Cloudy", humidity: 55, windSpeed: 10, flag: "https://flagcdn.com/w320/ar.png" },
    { country: "Netherlands", temperature: 36, condition: "Sunny", humidity: 45, windSpeed: 12, flag: "https://flagcdn.com/w320/nl.png" },
    { country: "Switzerland", temperature: 35, condition: "Partly Cloudy", humidity: 50, windSpeed: 10, flag: "https://flagcdn.com/w320/ch.png" },
    { country: "Belgium", temperature: 37, condition: "Sunny", humidity: 50, windSpeed: 11, flag: "https://flagcdn.com/w320/be.png" },
    { country: "Sweden", temperature: 35, condition: "Partly Cloudy", humidity: 45, windSpeed: 14, flag: "https://flagcdn.com/w320/se.png" },
    { country: "Norway", temperature: 36, condition: "Sunny", humidity: 40, windSpeed: 13, flag: "https://flagcdn.com/w320/no.png" },
    { country: "Finland", temperature: 35, condition: "Partly Cloudy", humidity: 50, windSpeed: 12, flag: "https://flagcdn.com/w320/fi.png" },
    { country: "Denmark", temperature: 37, condition: "Sunny", humidity: 45, windSpeed: 11, flag: "https://flagcdn.com/w320/dk.png" },
    { country: "Ireland", temperature: 36, condition: "Partly Cloudy", humidity: 50, windSpeed: 13, flag: "https://flagcdn.com/w320/ie.png" },
    { country: "Portugal", temperature: 40, condition: "Sunny", humidity: 35, windSpeed: 10, flag: "https://flagcdn.com/w320/pt.png" },
    { country: "Austria", temperature: 38, condition: "Partly Cloudy", humidity: 50, windSpeed: 12, flag: "https://flagcdn.com/w320/at.png" },
    { country: "Poland", temperature: 36, condition: "Sunny", humidity: 45, windSpeed: 11, flag: "https://flagcdn.com/w320/pl.png" },
    { country: "Hungary", temperature: 39, condition: "Sunny", humidity: 40, windSpeed: 10, flag: "https://flagcdn.com/w320/hu.png" },
    { country: "Czech Republic", temperature: 37, condition: "Partly Cloudy", humidity: 45, windSpeed: 12, flag: "https://flagcdn.com/w320/cz.png" },
    { country: "Greece", temperature: 45, condition: "Sunny", humidity: 30, windSpeed: 10, flag: "https://flagcdn.com/w320/gr.png" },
    { country: "Turkey", temperature: 42, condition: "Sunny", humidity: 35, windSpeed: 12, flag: "https://flagcdn.com/w320/tr.png" },
    { country: "South Korea", temperature: 38, condition: "Partly Cloudy", humidity: 55, windSpeed: 11, flag: "https://flagcdn.com/w320/kr.png" },
    { country: "Malaysia", temperature: 40, condition: "Cloudy", humidity: 70, windSpeed: 10, flag: "https://flagcdn.com/w320/my.png" },
    { country: "Singapore", temperature: 37, condition: "Partly Cloudy", humidity: 75, windSpeed: 8, flag: "https://flagcdn.com/w320/sg.png" },
    { country: "Indonesia", temperature: 39, condition: "Cloudy", humidity: 80, windSpeed: 9, flag: "https://flagcdn.com/w320/id.png" },
    { country: "Philippines", temperature: 41, condition: "Sunny", humidity: 85, windSpeed: 7, flag: "https://flagcdn.com/w320/ph.png" },
    { country: "Thailand", temperature: 44, condition: "Sunny", humidity: 80, windSpeed: 8, flag: "https://flagcdn.com/w320/th.png" },
    { country: "Vietnam", temperature: 40, condition: "Partly Cloudy", humidity: 85, windSpeed: 9, flag: "https://flagcdn.com/w320/vn.png" },
    { country: "New Zealand", temperature: 35, condition: "Cloudy", humidity: 65, windSpeed: 12, flag: "https://flagcdn.com/w320/nz.png" },
    { country: "Chile", temperature: 38, condition: "Rainy", humidity: 50, windSpeed: 10, flag: "https://flagcdn.com/w320/cl.png" },
    { country: "Colombia", temperature: 36, condition: "Partly Cloudy", humidity: 60, windSpeed: 11, flag: "https://flagcdn.com/w320/co.png" },
    { country: "Peru", temperature: 35, condition: "Sunny", humidity: 65, windSpeed: 10, flag: "https://flagcdn.com/w320/pe.png" },
    { country: "Egypt", temperature: 46, condition: "Sunny", humidity: 20, windSpeed: 12, flag: "https://flagcdn.com/w320/eg.png" },
    { country: "Saudi Arabia", temperature: 49, condition: "Sunny", humidity: 15, windSpeed: 18, flag: "https://flagcdn.com/w320/sa.png" },
    { country: "United Arab Emirates", temperature: 50, condition: "Sunny", humidity: 30, windSpeed: 15, flag: "https://flagcdn.com/w320/ae.png" },
    { country: "Israel", temperature: 43, condition: "Sunny", humidity: 35, windSpeed: 12, flag: "https://flagcdn.com/w320/il.png" },
    { country: "Morocco", temperature: 38, condition: "Partly Cloudy", humidity: 60, windSpeed: 10, flag: "https://flagcdn.com/w320/ma.png" },
    { country: "USA", temperature: 38, condition: "Partly Cloudy", humidity: 60, windSpeed: 10, flag: "https://flagcdn.com/w320/us.png"},
    { country: "Kenya", temperature: 35, condition: "Partly Cloudy", humidity: 50, windSpeed: 12, flag: "https://flagcdn.com/w320/ke.png" },
    { country: "Nigeria", temperature: 37, condition: "Sunny", humidity: 65, windSpeed: 10, flag: "https://flagcdn.com/w320/ng.png" },
    { country: "Ethiopia", temperature: 36, condition: "Partly Cloudy", humidity: 60, windSpeed: 11, flag: "https://flagcdn.com/w320/et.png" },
    { country: "Ghana", temperature: 38, condition: "Sunny", humidity: 70, windSpeed: 9, flag: "https://flagcdn.com/w320/gh.png" },
    { country: "Pakistan", temperature: 42, condition: "Rainy", humidity: 70, windSpeed: 9, flag: "https://flagcdn.com/w320/pk.png" },
];

export default weatherData;
